apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: runday
  name: running
  labels:
    app: running
spec:
  replicas: 1
  selector:
    matchLabels:
      app: running
  template:
    metadata:
      labels:
        app: running
    spec:
      containers:
        - name: running
          image: yurengel/running:v1
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
