apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: runday
  name: running
  labels:
    app: running
spec:
  replicas: 1
  selector:
    matchLabels:
      app: running
  template:
    metadata:
      labels:
        app: running
    spec:
      containers:
        - name: running
          image: yurengel/running:v1
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "200m"

              
          env:
            - name: RUNNING_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                   name: config-dev
                   key: RUNNING_LOG_LEVEL
          # volumeMounts:
          # - mountPath: "/mnt/data"
          #   name: volume
          # readinessProbe:
          #   httpGet:
          #     path: '/actuator/health'
          #     port: 8080
          #   initialDelaySeconds: 10
          #   timeoutSeconds: 2
          #   periodSeconds: 5
          #   failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            successThreshold: 1
            periodSeconds: 5
            failureThreshold: 3
      # volumes:
      # - name: volume
      #   persistentVolumeClaim:
      #     claimName: nfs-pvc      