server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: Running
          uri: http://localhost:8082
          predicates:
            - Path=/runnings/**, 
        - id: Rank
          uri: http://localhost:8083
          predicates:
            - Path=/rankings/**, 
        - id: FriendRelation
          uri: http://localhost:8084
          predicates:
            - Path=/friends/**, /likes/**, 
        - id: Logging
          uri: http://localhost:8085
          predicates:
            - Path=/logs/**, 
        - id: Notification
          uri: http://localhost:8086
          predicates:
            - Path=/messages/**, 
        - id: Dashboard
          uri: http://localhost:8087
          predicates:
            - Path=, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: Running
          uri: http://running:8080
          predicates:
            - Path=/runnings/**, 
        - id: Rank
          uri: http://rank:8080
          predicates:
            - Path=/rankings/**, 
        - id: FriendRelation
          uri: http://friendRelation:8080
          predicates:
            - Path=/friends/**, /likes/**, 
        - id: Logging
          uri: http://logging:8080
          predicates:
            - Path=/logs/**, 
        - id: Notification
          uri: http://notification:8080
          predicates:
            - Path=/messages/**, 
        - id: Dashboard
          uri: http://dashboard:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
